### ISSUE TITLE
Initiate potad and potac with grpc

### ISSUE THREAD

**Issue by iputra** [potacloud/pota#2]
- [x] potad
- [x] potac

**Comment by prastamaha** [comment]
I have created pota.yml to hold main configuration for potad and potac, then I read it into code using viper module

pota.yml looks like this
```
socket: "/home/prasta/program/goProject/pota/pota/potad.sock"

potad:
  timeout: 5

potac:
  timeout: 5
```

temporarily, I put this configuration in `github.com/potacloud/pota/pota/config/pota.yml`

we can add more value to pota.yml in the future as we need
